Galaxy Buds Client/BudsPopup.xaml
Galaxy Buds Client/BudsPopup.xaml.cs
Galaxy Buds Client/MainWindow.xaml.cs

Hi.
I already made a PR yesterday adding a connection popup, but you said that the code needed [a few changes](https://github.com/ThePBone/GalaxyBudsClient/pull/12#issuecomment-660671923).
Now, I made the changes and hopefully there will be no issues with my new code.
Here's what the popup looks like now:

Add a connection popup, again

---

README_kor.md

Korean README_kor.md

---

Galaxy Buds Client/i18N/ja.xaml
Galaxy Buds Client/i18N/ko.xaml

- Edited \n and some untranslated texts in ko.xaml
- Edited some texts in ja.xaml

Edit localization files

---

README.md

- Add Japanese README
- Add Japanese link in Original English README
- Edit some expression

Add Japanese README and edit some texts

---

Galaxy Buds Client/i18N/ja.xaml
README_jpn.md
README_kor.md

Sorry
I miscreated pull request :(
You can see new README by merging this XD

Recreate pull request about README

---

Galaxy Buds Client/i18N/pt.xaml

First of all, I love this project.
Second, I added a Portuguese translation.

Add portuguese translation

---

Galaxy Buds Client/i18N/cn.xaml
README.md
README_chs.md

* Translate untranslated strings
* Adjust inaccurate translations and synchronize some words with the translation of official Samsung Wearable app

Update Chinese Translation

---

Galaxy Buds Client/i18N/pl.xaml

Hello, I've just created polish translation file to GalaxyBudsManager. Could you possibly have a look at my file and add it as a new language to GalaxyBudsManager. Best regards Buashei :)

Added Polish Translation File, pl.xaml

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/crash-report.md
.github/ISSUE_TEMPLATE/feature_request.md
Galaxy Buds Client/i18N/ru.xaml
Galaxy Buds Client/i18N/ua.xaml

Hi there! Hope you're doing great in those trying times... I am currently in a quarantine hellhole - my university education was, let's say not great and with remote education it is outright pathetic. But, to business.
1. Issue templates. I don't know how do you like them and will you need to activate them manually in you repository settings, but either way I hope you'll take templates I've prepared.
2. I still haven't updated READMEs with new translators and other stuff because of point 3.
3. Repository wiki. That will be better for everybody. BUT! Unfortunately GitHub is incredibly dumb when it comes to wikis so you'll need to do some tinkering in order to copy my version...
3.1. Create a wiki with a blank Home page
3.2. Do this on your PC
> git clone …

Edit package 06122020

---

Galaxy Buds Client/i18N/ko.xaml
README_kor.md

Update Korean Translation and README

---

GalaxyBudsClient/i18n/it.xaml

Note: developer mode strings are still missing. This pull request addresses only the strings of the main application.

Update/Optimize Italian Translation

---

GalaxyBudsClient/i18n/it.xaml

Added italian localization for _EventDispatcher module_ and _Advanced page_ strings.

Update Italian Translation 

---

GalaxyBudsClient/i18n/ko.xaml

Text corruption fix
Translation consistency
Translation accuracy

Translation update

---

GalaxyBudsClient/i18n/cz.xaml
GalaxyBudsClient/i18n/en.xaml
README.md
docs/README_chs.md
docs/README_cze.md
docs/README_jpn.md
docs/README_kor.md
docs/README_rus.md
docs/README_ukr.md

I created and translated the Czech version of README.md, added links to it in other READMEs, updated the cz.xaml file.

Created README_cze.md (and translated to Czech) and translated/updated cz.xaml.

---

GalaxyBudsClient/i18n/cz.xaml
README.md
docs/README_cze.md

Corrected Czech translation in cz.xaml and in README_cze.md. 
Added missed phrases in cz.xaml, translated forgotten sentence in README_cze.md.

Czech translation - correction

---

GalaxyBudsClient/Model/Constants.cs
GalaxyBudsClient/i18n/gr.xaml

I added the greek translation following the steps in the wiki. I may translate the README.md in the future. If there is an issue please let me know.
Thank you!

Added greek translation

---

GalaxyBudsClient/i18n/gr.xaml
README.md
docs/README_chs.md
docs/README_cze.md
docs/README_gr.md
docs/README_jpn.md
docs/README_kor.md
docs/README_rus.md
docs/README_ukr.md

I added the README_gr.md file with the greek translation of the README.md file. I updated the other README.md files with the link to the greek translation and I added myself as the translator for the Greek language in README.md and README_gr.md. I also corrected some minor issues with the greek translation of the app.

Added greek README.md file and corrected minor greek translation mistakes

---

GalaxyBudsClient/i18n/cz.xaml
meta/cz.md
meta/translations.md

Added and translated 49 strings.

Czech translation update

---

GalaxyBudsClient/i18n/ko.xaml

Added missing translations
(noise control, firmware updater)
Fixed strings

Korean translation update

---

GalaxyBudsClient/i18n/ko.xaml
meta/ko.md
meta/translations.md

Reverts ThePBone/GalaxyBudsClient#202

Revert "Korean translation update"

---

GalaxyBudsClient/i18n/cz.xaml
docs/README_cze.md

Updated Czech readme and updated translation on three-way string

Czech translation updates

---

GalaxyBudsClient/Model/Constants.cs
GalaxyBudsClient/i18n/ro.xaml

I used the app to boost my Galaxy Buds Live experience and I decided to contribute by providing Romanian translation.

Complete Romanian translation

---

README.md
docs/README_cze.md

Czech readme should be up-to-date. 
Fixed header level in main README

Czech README update

---

GalaxyBudsClient/Interface/Styles/Base.xaml
README.md
docs/README_chs.md
docs/README_cze.md
docs/README_gr.md
docs/README_rus.md
docs/README_ukr.md

Updated my username in all files

Updated my username in all files

---

docs/README_jpn.md
docs/README_kor.md

Update KOR, JPN README

---

docs/README_cht.md

Added README translation file for Traditional Chinese.
Part of the translation has not been completed.

Added README translation file for Traditional Chinese

---

README.md
docs/README_cht.md

Traditional Chinese README file translation

Traditional Chinese README file translation

---

GalaxyBudsClient/i18n/de.xaml

I updated the translation file for de (German) to include all the missing Strings from the en language file.
If you should see any error or other complications just contact me any time :)
I hope I could help
- benni 😄

Updated de language file to include all missing Strings

---

GalaxyBudsClient/Model/Constants.cs
GalaxyBudsClient/i18n/il.xaml

* Updated existing translations
* Added missing translations
* Fixed country code
Unfortunately had to mess with some formatting to get it to format properly due to no RTL support.

Hebrew translation updates

---

meta/es.md

Translated all strings into Spanish

Patch 2 - Completed translation

---

GalaxyBudsClient/i18n/ru.xaml

Made the russian version more clear and undestandable, corrected some mistakes and typos.
Added almost all missing strings.

Russian translation update

---

docs/README_cht.md

Updates and translation corrections

Traditional Chinese markdown file update

---

GalaxyBudsClient/i18n/cn.xaml

fix title translation, and add more details in description.

update chinese translation of double tap volume

---

GalaxyBudsClient/i18n/it.xaml

I added "Manual pairing" section, "Buds app detected page" section, "Header" section, "Spatial test" section and "Firmware transfer errors" section,

Update italian translation

---

GalaxyBudsClient/Model/Firmware/FirmwareRemoteClient.cs

Not sure about localhost one ;)
Some discussion in #361

Update api url to use /v2

---

README.md
docs/README_chs.md
docs/README_cht.md
docs/README_cze.md
docs/README_gr.md
docs/README_jpn.md
docs/README_kor.md
docs/README_pt.md
docs/README_rus.md
docs/README_ukr.md

Hello, just a translation of the README file to portuguese, also added the href to the translation on the others README files

Portuguese README FILE

---

GalaxyBudsClient/Model/Constants.cs
GalaxyBudsClient/i18n/nl.xaml

I've translated the GalaxyBudsClient in Dutch (The Netherlands).

Added a Dutch language

---

GalaxyBudsClient/MainWindow.xaml.cs

this should fix #407 , it checks the received close event before cancelling

fix application shutdown event under KDE plasma

---

GalaxyBudsClient/i18n/tr.xaml
README.md
docs/README_tr.md

- Added a Turkish README file.
- The access link to the Turkish User Guide has been added to the main README file.
- Improved Turkish translations for accuracy and clarity.
- All missing translations have been completed for Turkish.

The Turkish translation has been updated.

---

GalaxyBudsClient/i18n/tr.axaml

All necessary edits have been made and all strings that needed to be added have been added.

All Turkish translations have been completed.

---

GalaxyBudsClient/i18n/cz.axaml
GalaxyBudsClient/i18n/tr.axaml

Minor translation deficiencies have been corrected.
Translations of new words completed.

Minor Changes

---

install.nsi

https://github.com/microsoft/winget-pkgs/pull/154302#issuecomment-2121030414

Update install.nsi to reference new GitHub alias

---

GalaxyBudsClient/i18n/ko.axaml
meta/ko.md
meta/translations.md

This is 1st phase for translate, will keep update it.

Update Korean Translate

---

GalaxyBudsClient/i18n/en.axaml
GalaxyBudsClient/i18n/vn.axaml
README.md
docs/README_chs.md
docs/README_cht.md
docs/README_cze.md
docs/README_gr.md
docs/README_jpn.md
docs/README_kor.md
docs/README_pt.md
docs/README_rus.md
docs/README_tr.md
docs/README_ukr.md
docs/README_vnm.md

The app's translation file was so old and outdated, I decided to just re-translate the newest `en.axaml` again 
(Also the really small changes for English, just my OCD sorry xD. I can reverse them if deemed unnecessary)

Vietnamese translations 

---

GalaxyBudsClient/i18n/tr.axaml

Added missing turkish translations

Update turkish translations

---

README.md
docs/README_kor.md

@timschneeb 
Updated README_kor.md to be up to date!
I also changed the image links from blob to raw.
Please review my PR and feel free to give me feedback!

Update README.md & README_kor.md
