timschneeb/GalaxyBudsClient

Galaxy Buds Client/ui/DeviceSelectPage.xaml.cs
Add Buds Live option to the RegisteredDeviceModel selection logic. With this addition, I see no issues on my Buds Live.
=> Add Buds Live to RegisteredDeviceModel selection logic

GalaxyBudsClient/i18n/ko.xaml
The current translation overflows the header:
This commit shortens the translation so that it matches the English phrasing and doesn't overflow.
=> Shorten Korean translation

README.md
I've added the package to Windows Package Manager ([winget](https://github.com/microsoft/winget-cli)), it can be installed with `winget install ThePBone.GalaxyBudsClient`. The pull request adds the instruction to the readme (and credits).
=> Added WinGet install instructions

GalaxyBudsClient.sln, GalaxyBudsClient/GalaxyBudsClient.csproj, GalaxyBudsClient/Interface/Pages/AbstractPage.cs, GalaxyBudsClient/Interface/Pages/BudsAppDetectedPage.xaml, GalaxyBudsClient/Interface/Pages/BudsAppDetectedPage.xaml.cs, GalaxyBudsClient/Interface/Pages/WelcomePage.xaml.cs, GalaxyBudsClient/MainWindow.xaml.cs, GalaxyBudsClient/app.manifest, GalaxyBudsClient/i18n/en.xaml
I noticed that Galaxy Buds Manager doesn't connect to my buds when the [official Galaxy Buds app for Windows](https://www.microsoft.com/store/productId/9NHTLWTKFZNB) is installed.
I added a warning message for those who use both apps.
It only checks if the Buds app is installed because I can't get a list of running UWP apps.
=> Detect the official Galaxy Buds app

GalaxyBudsClient/GalaxyBudsClient.csproj
I changed the Linux config to `InvariantGlobalization = true` because the app crashed on Arch systems and this is a working fix as discussed on #334.
Relevant:
https://learn.microsoft.com/en-us/dotnet/core/runtime-config/globalization
=> Fix Linux Globalization crash

GalaxyBudsClient/Interface/Elements/LoadingSpinner.xaml, GalaxyBudsClient/Interface/Elements/LoadingSpinner.xaml.cs
Hello. So, on Linux with Nvidia proprietary drivers (didn't have a chance to test it on an AMD GPU), I had an issue where my CPU core goes to 100% usage. It happens whenever LoadingSpinner's IsVisible property sets to true at least one time. And LoadingSpinner has a spinning animation which causes high CPU core usage. For example, in https://github.com/ThePBone/GalaxyBudsClient/blob/master/GalaxyBudsClient/Interface/Pages/HomePage.xaml.cs, _loadingSpinner IsVisible property sets to true at least one time but the animation of it will keep working even after we set it to false.
My workaround is to just stop the animation whenever we get IsVisible property set to false. It's not the best solution because it would be better to actually fix the animation performance issue, but at least this …
=> Linux performance issue

GalaxyBudsClient.Bluetooth.Linux/BluetoothService.cs
When you try to open up the app after your earbuds are paired and connected, it will throw you this error: "org.bluez.Error.Failed Operation already in progress". This happens because the BluetoothService attempts to connect to an already connected device. I see that in the code you expect BlueZException to be thrown with the error code "AlreadyConnected", but that usually doesn't happen, and instead you get the "Failed" error code with the above-mentioned error message. This is what basically causes the bug. And to fix this issue, we just need to check if the device already connected. It is easily fixable with just two lines of code.
Has anyone encountered this issue before? Because it looks like a common issue
=> Fix annoying Linux bluetooth connection bug

GalaxyBudsClient/Message/Decoder/ExtendedStatusUpdateParser.cs
This combined with 7fd0a41 fixes touchpad lock feature for Buds2 familiy. (Tested on Buds2 only)
=> Fix inverted touchpad lock reading on Buds2/Buds2Pro

GalaxyBudsClient/Interface/Pages/AdvancedPage.xaml, GalaxyBudsClient/Interface/Pages/AdvancedPage.xaml.cs
=> Fix: Bixby not visible when hotkeys not supported

GalaxyBudsClient.Bluetooth.WindowsRT/GalaxyBudsClient.Bluetooth.WindowsRT.csproj, GalaxyBudsClient/GalaxyBudsClient.csproj, GalaxyBudsClient/Interface/Dialogs/BudsPopup.xaml, GalaxyBudsClient/Interface/Dialogs/BudsPopup.xaml.cs, GalaxyBudsClient/Interface/Pages/SystemPage.xaml.cs, GalaxyBudsClient/MainWindow.xaml, ThePBone.OSX.Native/Native/src/HotkeyManager.swift, ThePBone.OSX.Native/ThePBone.OSX.Native.csproj, global.json
Fixes:
1. macOS hotkey editor uses physical QWERTY key labels on all layouts (though it does also press the same key)
This is unblocked by Avalonia 11 upgrade
macOS code already exists and ~~just needs to be~~ now is uncommented: https://github.com/ThePBone/GalaxyBudsClient/blob/d48faff0118538887f4f5beb4854507bda9afb92/ThePBone.OSX.Native/Native/src/HotkeyManager.swift#L394-L403
2. Generated installer .PKG file has version 1.0
3. If Galaxy Buds Manager main window is open and NOT minimized-to-tray, and battery info popup closes, the main window will go to front
4. Firmware updates are untested, and hence disabled. -> They are now enabled, but untested anyways.
=> fix some macos bugs

GalaxyBudsClient/Interface/Dialogs/HotkeyActionBuilder.xaml.cs, GalaxyBudsClient/Interface/Dialogs/HotkeyRecorder.xaml.cs, GalaxyBudsClient/Interface/Dialogs/InputDialog.xaml.cs, GalaxyBudsClient/Interface/Dialogs/ManualPairDialog.xaml.cs, GalaxyBudsClient/Interface/Dialogs/MessageBox.xaml.cs, GalaxyBudsClient/Interface/Dialogs/QuestionBox.xaml.cs, GalaxyBudsClient/Interface/Pages/DeviceSelectionPage.xaml.cs, ThePBone.OSX.Native/Native/src/HotkeyManager.swift
Fixes:
1. macOS hotkey dispatching does not support 100% of keys
- Not everything seems to match perfectly (exist on both keyboards) between Win32/Avalonia keycodes and macOS keycodes
- -> how does Avalonia map these keys?
- https://github.com/ThePBone/GalaxyBudsClient/blob/d48faff0118538887f4f5beb4854507bda9afb92/ThePBone.OSX.Native/Native/src/HotkeyManager.swift#L53-L214
2. If you open any UI dialog (in the whole app), examples being "Override popup title" in settings, and closing it again, the either main window will open the dialog again on a click anywhere and will highlight the button if the mouse hovers over the window, and you have to restart the app to click anything else / get out.
=> Fix another bunch of macOS bugs

.github/workflows/compile-macos.yml, GalaxyBudsClient/GalaxyBudsClient.csproj, ThePBone.OSX.Native/Native/NativeInterop.xcodeproj/project.pbxproj, ThePBone.OSX.Native/Native/NativeInterop.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved, ThePBone.OSX.Native/Native/NativeInterop.xcodeproj/xcshareddata/xcschemes/NativeInterop.xcscheme, ThePBone.OSX.Native/Native/src/HotkeyManager.swift, ThePBone.OSX.Native/ThePBone.OSX.Native.csproj
Fixes some build flakiness issues by regenerating Xcode project, ensures parameters like min OS version aren't dependant on build machine and then adds working x64+arm64 binaries to artifacts.
=> Add macOS CI

.github/workflows/compile-macos.yml, GalaxyBudsClient/App.xaml.cs, GalaxyBudsClient/GalaxyBudsClient.csproj, GalaxyBudsClient/MainWindow.xaml.cs, GalaxyBudsClient/Program.cs, GalaxyBudsClient/nuget.config
I split up the tracker issue into two seperate issues linking to the Avalonia bug reports, because I can't do anything about those.
But those bugs aren't deal-breakers, and that's why I'm happy to announce the macOS port of GalaxyBudsClient is stable now. :D
=> The final bunch of macOS fixes (for now)

.github/workflows/compile-macos.yml
While this sacrifice hurts (doubled binary size), Config.NET/Castle.DynamicProxy breaks with TrimMode=Full
=> CI: remove TrimMode=Full

.github/workflows/compile-macos.yml, GalaxyBudsClient/GalaxyBudsClient.csproj, GalaxyBudsClient/Info.plist, GalaxyBudsClient/Interface/Pages/AmbientSoundPage.xaml.cs, GalaxyBudsClient/Interface/Pages/BixbyRemapPage.xaml.cs, GalaxyBudsClient/Interface/Pages/HomePage.xaml.cs, GalaxyBudsClient/Interface/Pages/TouchpadPage.xaml.cs, GalaxyBudsClient/MainWindow.xaml.cs, GalaxyBudsClient/Message/MessageComposer.cs, GalaxyBudsClient/Model/EventDispatcher.cs, GalaxyBudsClient/Utils/LocalizationUtils.cs, GalaxyBudsClient/Utils/ThemeUtils.cs, GalaxyBudsClient/Utils/TrayManager.cs
- Set app name to user friendly name
- Fix double title bar
- Fix tray icon crash by updating the tray icon only when needed and while it's closed
=> fixes for macOS

GalaxyBudsClient/Interface/CustomTitleBar.xaml, GalaxyBudsClient/MainWindow.xaml
In MainWindow.xaml I had to hardcode the `CornerRadius` to 20 instead of getting it from the `DefaultCornerRadius` value because `<Border CornerRadius="{OnPlatform Default={StaticResource DefaultCornerRadius}, macOS='10'}"` would cause the app to not open for some reason.
=> Better macOS window

GalaxyBudsClient/Utils/Interface/WindowIconRenderer.cs
Fixes bug where icon doesn't show the proper battery level for the right bud if "show lowest battery level" is selected
=> Bug fix for #519

GalaxyBudsClient/Interface/Controls/EarbudIcon.cs, GalaxyBudsClient/Interface/MarkupExtensions/DeviceColorBindingSource.cs, GalaxyBudsClient/Interface/Pages/SettingsPage.axaml, GalaxyBudsClient/Model/Config/SettingsData.cs, GalaxyBudsClient/i18n/en.axaml, GalaxyBudsClient/i18n/tr.axaml
Adds a combo box in the settings page under "Appearance" that lists the possible colors for the user to choose from, and overrides the earbud images with the color selected.
Closes #579
=> Feature: Earbud color override

GalaxyBudsClient/App.axaml, GalaxyBudsClient/App.axaml.cs
Added Styles to fix title bar color overlay.
ISSUE #578 
---- Fix
**Inactive looks**
**Hover looks**
----- Notes
- I tried to create direct Binding to FluentTheme.CustomAccentColor or the Settings.CustomAccentColor, But I was not able to. It didn't work unfortunately.  So, I had to create a resource.
- I think this is an issue or a bug related to FluentTheme. In the code, the titleBarOverlay colors is set from the accent color, however for some reason, the accent color doesn't reflect the customAccentColor. [Reference](https://github.com/amwx/FluentAvalonia/blob/v2.0.4/src/FluentAvalonia/UI/Windowing/AppWindow/AppWindow.cs#L353).
- Lastly, this was not tested either on Mac or Linux, so no idea how they will look.
=> added styles to fix title bar control colors

GalaxyBudsClient/Interface/Controls/EarbudStatusUnit.axaml.cs, GalaxyBudsClient/Interface/ViewModels/Controls/EarbudStatusUnitViewModel.cs
This pull request fixes the crash caused by updating UI-bound properties from a background thread. Only the following two files were modified:
- **EarbudStatusUnit.cs**: Modified the subscription in the constructor to wrap the calls to `LeftBatteryText.InvalidateMeasure()` and `RightBatteryText.InvalidateMeasure()` in `Dispatcher.UIThread.Post(...)`.
- **EarbudStatusUnitViewModel.cs**: Wrapped UI-updating calls in the event handlers (such as in `OnStatusUpdated`, `OnBluetoothPropertyChanged`, and `OnMainSettingsPropertyChanged`) in `Dispatcher.UIThread.Post(...)`.
Fixes #593
These changes follow a pattern already present in the code (see `RenamePageViewModel` for example) and should resolve the cross-thread UI violation without affecting other parts of the application.
=> Fix cross-thread UI calls in EarbudStatusUnit (#593)

GalaxyBudsClient/Interface/Converters/DeviceSelectStateConverter.cs
**Summary**
This PR prevents the app from crashing when the Bluetooth/Devices tab is opened repeatedly. It replaces the thrown exceptions in `DeviceSelectStateConverter` with safe fallback returns. This resolves the crash reported in #580 and #597.
**Details**
- Removes the `throw new ArgumentException(...)` calls.
- Returns `null` for unsafe or invalid binding values.
**Testing**
- On Windows and Linux, quickly switched tabs (Bluetooth <-> Home) multiple times and the app no longer crashes.
- No regression found in normal usage.
**Closes #580**  
**Closes #597**
=> Fix crash in DeviceSelectStateConverter when switching to Bluetooth tab (#580, #597)

GalaxyBudsClient/i18n/ru.axaml, docs/README_rus.md
**Description:**  
This pull request updates and improves the Russian translation for the application. Specifically, it addresses missing strings by adding translations for 235 strings and removing out-of-date entries that are no longer in the original source text. In addition, `README_rus.md` is updated to match the latest content in the main `README.md`.
**Summary of Changes:**  
1. **`ru.axaml`** – Added or updated translations for all relevant strings.  
2. **Removed out-of-date strings** – Cleaned up translation entries that no longer exist in the original.  
3. **`README_rus.md`** – Brought in line with the main `README.md` for consistency.
**Known Issues / Additional Notes:**  
- The resource string `<sys:String x:Key="not_available">Недоступно</sys:String>` does not seem to appear …
=> Update Russian translation and README_rus.md

GalaxyBudsClient/Model/Constants.cs, GalaxyBudsClient/i18n/br.axaml, README.md, docs/README_vnm.md
This pull request introduces a new locale for Brazilian Portuguese to the `Locales` enum and makes minor corrections to contributor listings in both the English and Vietnamese README files. The most significant change is the addition of the Brazilian Portuguese locale, expanding language support in the application.
**Localization update:**
* Added `br` (Portuguese Brazil) to the `Locales` enum in `GalaxyBudsClient/Model/Constants.cs` to support Brazilian Portuguese.
**Documentation corrections:**
* Fixed formatting in the Chinese translation contributor list in `README.md` by removing a duplicated asterisk and the name `JuanFariasDev`.
* Applied the same formatting fix for the Chinese translation contributor list in `docs/README_vnm.md`.
=> Add portuguese Brazil
